//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumbo.Web.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bumbo.Web.Resources.Views.Home.Index.nl", typeof(Index_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afwezig wegens ziekte.
        /// </summary>
        internal static string Absent_due_to_illness {
            get {
                return ResourceManager.GetString("Absent due to illness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verjaardagen.
        /// </summary>
        internal static string Birthdays {
            get {
                return ResourceManager.GetString("Birthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druk.
        /// </summary>
        internal static string Crowded {
            get {
                return ResourceManager.GetString("Crowded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwachte drukte.
        /// </summary>
        internal static string Expected_crowds {
            get {
                return ResourceManager.GetString("Expected crowds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prognose komende week.
        /// </summary>
        internal static string Forecast_upcoming_week {
            get {
                return ResourceManager.GetString("Forecast upcoming week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuis.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemiddeld.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuws.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplande uren.
        /// </summary>
        internal static string Planned_hours {
            get {
                return ResourceManager.GetString("Planned hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rustig.
        /// </summary>
        internal static string Quiet {
            get {
                return ResourceManager.GetString("Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen zieke werknemers..
        /// </summary>
        internal static string There_are_no_sick_employees_ {
            get {
                return ResourceManager.GetString("There are no sick employees.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen aanstaande verjaardagen.
        /// </summary>
        internal static string There_are_no_upcoming_birthdays {
            get {
                return ResourceManager.GetString("There are no upcoming birthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is nog geen nieuws..
        /// </summary>
        internal static string There_is_no_news_yet_ {
            get {
                return ResourceManager.GetString("There is no news yet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onbekend.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weersvoorspelling.
        /// </summary>
        internal static string Weather_forecast {
            get {
                return ResourceManager.GetString("Weather forecast", resourceCulture);
            }
        }
    }
}
