//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumbo.Web.Resources.Views.Branches {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Details_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bumbo.Web.Resources.Views.Branches.Details.nl", typeof(Details_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager toevoegen.
        /// </summary>
        internal static string Add_manager {
            get {
                return ResourceManager.GetString("Add manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar overzicht.
        /// </summary>
        internal static string Back_to_List {
            get {
                return ResourceManager.GetString("Back to List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filiaal.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidige managers.
        /// </summary>
        internal static string Current_managers {
            get {
                return ResourceManager.GetString("Current managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanpassen.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadres.
        /// </summary>
        internal static string Email_address {
            get {
                return ResourceManager.GetString("Email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        internal static string First_name {
            get {
                return ResourceManager.GetString("First name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer.
        /// </summary>
        internal static string House_number {
            get {
                return ResourceManager.GetString("House number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        internal static string Last_name {
            get {
                return ResourceManager.GetString("Last name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussenvoegsel.
        /// </summary>
        internal static string Middle_name {
            get {
                return ResourceManager.GetString("Middle name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string Zip_code {
            get {
                return ResourceManager.GetString("Zip code", resourceCulture);
            }
        }
    }
}
