//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumbo.Web.Resources.Views.Forecast {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangeNorms_nl {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeNorms_nl() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bumbo.Web.Resources.Views.Forecast.ChangeNorms_nl", typeof(ChangeNorms_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Back_to_list {
            get {
                return ResourceManager.GetString("Back to list", resourceCulture);
            }
        }
        
        internal static string CASHIER {
            get {
                return ResourceManager.GetString("CASHIER", resourceCulture);
            }
        }
        
        internal static string FACE_SHELVES {
            get {
                return ResourceManager.GetString("FACE_SHELVES", resourceCulture);
            }
        }
        
        internal static string PRODUCE_DEPARTMENT {
            get {
                return ResourceManager.GetString("PRODUCE_DEPARTMENT", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string STOCK_SHELVES {
            get {
                return ResourceManager.GetString("STOCK_SHELVES", resourceCulture);
            }
        }
        
        internal static string UNLOAD_COLI {
            get {
                return ResourceManager.GetString("UNLOAD_COLI", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Change_norms {
            get {
                return ResourceManager.GetString("Change norms", resourceCulture);
            }
        }
        
        internal static string Worked_hours {
            get {
                return ResourceManager.GetString("Worked hours", resourceCulture);
            }
        }
    }
}
