//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumbo.Web.Resources.Models.AdditionalWork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IndexViewModel_AdditionalWork_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexViewModel_AdditionalWork_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bumbo.Web.Resources.Models.AdditionalWork.IndexViewModel+AdditionalWork.nl", typeof(IndexViewModel_AdditionalWork_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eindtijd.
        /// </summary>
        internal static string End_Time {
            get {
                return ResourceManager.GetString("End Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starttijd.
        /// </summary>
        internal static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De starttijd en de eindtijd moeten allebei zijn ingevuld op {0}..
        /// </summary>
        internal static string The_start_and_end_time_both_need_to_be_filled_in_on__0__ {
            get {
                return ResourceManager.GetString("The start and end time both need to be filled in on {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De starttijd kan niet na de eindtijd zijn op {0}..
        /// </summary>
        internal static string The_start_time_cannot_be_after_the_end_time_on__0__ {
            get {
                return ResourceManager.GetString("The start time cannot be after the end time on {0}.", resourceCulture);
            }
        }
    }
}
